version = 0.1
[default.deploy.parameters]
stack_name = "react-app-s3-cloudfront-sam"
resolve_s3 = true
s3_prefix = "react-app-s3-cloudfront-sam"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"react-app-s3-cloudfront-sam\""
image_repositories = []
